//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeveloperTask.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reminder
    {
        public long Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public System.DateTime Date { get; set; }
        [Required]

        public long CategoryId { get; set; }

        public Nullable<long> SubCategoryId { get; set; }
        public long CreatedBy { get; set; }
        public bool Disabled { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
